### PR TITLE
fix: improve screen reader behaviors on stack-view and modal

### LINKED ISSUE #3566: Stack view edit mode accessibility issues
## Describe the bug

The edit mode of stack view has several defects 

- The form fields are not labeled (should probably use new forms inputs)
- The stack-block-changed triangle needs a unique textual equivalent (when you've edited a field) Screen reader users will not hear what these shapes are meant to convey when they read them. It is important that part of the textual equivalent is unique, e.g., 'record 1 has changed' and 'record 2 has changed'.
- Close button doesn't have an accessible name
- Screen readers don't hear anything when edit dialog appears

## How to reproduce

https://stackblitz.com/github/clane/clarityTest2/tree/master/clarity-test-app

- Using a screen reader, go to the 'Stack View Edit' example
- Activate the Edit Button
- Observe you don't hear anything about the now opened edit dialog.
- Read any of the input fields and try to determine the purpose of any field.
- Edit a field
- Read any content or control visually associated with the stack-block-changed triangle. Notice that you do not hear what his shape is meant to convey. You would expect to hear something like 'One of Jon Doe's records has changed'. 
- Close button in edit mode is not accessible (may be solved by modal refactorings)

## Expected behavior

- Use aria-label to provide a unique accessible name for each input field.
- Use aria-label to provide a unique textual equivalent for the stack-block-changed triangle. The textual equivalent should reflect the context of each stack.
- While a stack is collapsed, Provide an 'id' attribute with the stack-block-changed triangle to be used with aria-describedby on the adjacent stack buttons. This will allow the stack-block-changed triangle(s) to provide the intended information to screen reader users.
- Use aria-label to provide and accessible name such as 'close stack edit mode dialog'
- Move focus to the modal title on open

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

This is a combination of several issues related to edit mode, some of which may be resolved in the modal itself already.

### PR DESCRIPTION
**Pull request by gnomeontherun**
This addresses screen reader issues with the stack-view, where labels
and inputs need to be linked with describedby, adds screenreader text
for indicating if a block has been changed (currently only a CSS
triangle shape), and moves the focus into the modal title for editing.

closes #3566

## PR Checklist

Please check if your PR fulfills the following requirements:

* [x] Tests for the changes have been added (for bug fixes / features)
* [x] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [x] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

* The stack view doesn't link the labels and input in edit mode unless the applications do it on their side.
* The stack view has a visual treatment for when a block has changed but it was not announced to screen readers.
* The focus remains on the trigger element for a modal open action. 

Issue Number: #3566 

## What is the new behavior?

* This will automatically link the label and input with an id/aria-describedby. 
* This adds offscreen text before the label to indicate the changed state.
* Focus is moved to the modal title when modal is opened (which is inside of the trap). 

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Other information

There is a change where the modal title has the focus outline on open since it becomes focused. This is an expected side effect, but visually we may get backlash for this visual behavior. Need to validate this behavior fully.

### CODE REVIEW

File: src/clr-angular/modal/modal.ts [hunk 1]
```diff
@@ -67,17 +72,10 @@ export class ClrModal implements OnChanges, OnDestroy {
...
   ) {}
 
-  get sizeClass(): string {
-    if (this.size) {
-      return 'modal-' + this.size;
-    } else {
-      return '';
-    }
-  }
-
```
Comment (jeeyun) [inline src/clr-angular/modal/modal.ts]: was this something we haven't been using for a while and just getting cleaned up here?

Comment (mathisscott) [reply src/clr-angular/modal/modal.ts]: yeah. we apparently moved away from interpolating that class string to do a `[class.modal-*]` boolean binding in modal.html

File: src/clr-angular/data/stack-view/stack-content-input.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+
+@Directive({
+  selector: 'clr-stack-content > input[type="text"]',
+  host: {
+    '[class.clr-input]': 'true',
+    '[attr.aria-describedby]': 'stackBlockService?.id',
+  },
+})
+export class ClrStackContentInput {
+  constructor(@Optional() public stackBlockService: StackBlockService) {}
```
Comment (mathisscott) [inline src/clr-angular/data/stack-view/stack-content-input.ts]: Is there a path whereby `stackBlockService` would not be defined?

File: src/clr-angular/data/stack-view/stack-block.ts [hunk 3]
```diff
@@ -84,16 +89,19 @@ export class ClrStackBlock implements OnInit {
...
     @Optional()
     private parent: ClrStackBlock,
+    public stackBlockService: StackBlockService,
+    @Inject(UNIQUE_ID) uniqueId: string,
     public commonStrings: ClrCommonStringsService
   ) {
     if (parent) {
       parent.addChild();
     }
+    this.stackBlockService.id = uniqueId;
```
Comment (Shijir) [inline src/clr-angular/data/stack-view/stack-block.ts]: Shouldn't we use the same concept as we used in our tooltip component? First, we need to check user-defined id before setting out own unique id?

Comment (gnomeontherun) [reply src/clr-angular/data/stack-view/stack-block.ts]: This sets the unique ID, and if the user sets one the input setter overrides it.

Comment (Shijir) [reply src/clr-angular/data/stack-view/stack-block.ts]: Do we have the input setter for id in this component? We are setting the id only here in the constructor?

Comment (gnomeontherun) [reply src/clr-angular/data/stack-view/stack-block.ts]: Look at the template and notice that the id is put into the `dt` element which is internalized. Therefore an ID provided on the stack block should not be moved into the child element.

File: src/clr-angular/data/stack-view/stack-content-input.ts (hunk 2 above)
Comment (gnomeontherun) [reply src/clr-angular/data/stack-view/stack-content-input.ts]: The problem was that I forgot Angular doesn't support child combinator selectors, so `clr-stack-block > input[type="text"]` was just turning into `input[type="text"]` and matching too many elements. I fixed this by making the directive selector unique but apps will need to add this directive to their inputs to get the behaviors to work properly.

File: src/clr-angular/data/stack-view/stack-block.ts (hunk 3 above)
Comment (Shijir) [reply src/clr-angular/data/stack-view/stack-block.ts]: Actually, I don't think we don't need to concern about user-defined ids. As the `dt` element is hidden in the stackblock's template.

File: src/clr-angular/data/stack-view/stack-block.service.ts [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+ * Copyright (c) 2016-2019 VMware, Inc. All Rights Reserved.
+ * This software is released under MIT license.
+ * The full license information can be found in LICENSE in the root directory of this project.
+ */
+
+import { Injectable } from '@angular/core';
+
+@Injectable()
+export class StackBlockService {
+  public id;
```
Comment (Shijir) [inline src/clr-angular/data/stack-view/stack-block.service.ts]: This is related to what I mentioned earlier. Users won't be able to set their own ids, as the element we set the unique id on is wrapped inside our component template. So If users don't need to set their own ids, we don't need this service the id.

As the stackblock component injects the unique id provider, all its children can inject and access the autogenerated id.

Comment (gnomeontherun) [reply src/clr-angular/data/stack-view/stack-block.service.ts]: Good catch, I had bigger plans originally but this service doesn't need to exist.

File: src/clr-angular/modal/modal.ts [hunk 5]
```diff
@@ -121,6 +119,8 @@ export class ClrModal implements OnChanges, OnDestroy {
   fadeDone(e: AnimationEvent) {
     if (e.toState === 'void') {
       this._openChanged.emit(false);
+    } else if (e.toState === 'false' && isPlatformBrowser(this.platformId) && this.modalTitle) {
```
Comment (Shijir) [inline src/clr-angular/modal/modal.ts]: Hmm. So this is now dependent on fadeDone animation callback. But looks like we already had `openChanged` dependent on fadeDone though. I think we could make use of *TODO* comment here to remind us to re-visit this later and decouple these from animation callback.

Comment (gnomeontherun) [reply src/clr-angular/modal/modal.ts]: Added a comment, though I don't recall having a discussion about not wanting to avoid animation callbacks so if we want to tackle that refactoring we should backlog a story about that.
