### PR TITLE
fix(datagrid): allow apps to disable focus management on page change

### LINKED ISSUE #4229: Datagrid steals focus on programmatic page change
## Describe the bug

When changing the page number via the input `[clrDgPage]="pageNumber"` the Datagrid focuses itself ([GoToCode](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid.ts#L254)). That is stealing the focus of other elements on the page, like in our case an important, autofocused input field.

## Expected behavior

A programmatically set page should not affect the focus state on the page.

## Versions

**App**

* Angular: 8.2.14
* Clarity: 2.3.4

**Device:**

* Browser: Chrome

### LINKED ISSUE #5374: Datagrid should not be stealing focus when the page change
## Describe the accessibility issue
In many places, we set Datagrid pagination page, size, ... programmatically. This trigger page changes observable and sets focus on Datagrid.

## WCAG Guideline
WCAG-G2.4.3 Level-A

## How to reproduce
https://stackblitz.com/edit/clarity-v4-light-theme-jj3zdt

1.  Go to 'https://stackblitz.com/edit/clarity-v4-light-theme-jj3zdt'
2.  Click on the 'Page' button
3.  This button set currentPage on Datagrid pagination 
4.  See the focus on Datagrid 

## Expected behavior
Datagrid should not be stealing focus when the page changes

## Versions

**App**

- Angular: [9.1.0]
- Clarity: [3.1.7]

**Device:**

- Type: [PC]
- OS: [Windows 10 (64-bit)]
- Browser [Google Chrome (Version )]
- Version [84.0.4147.135 (Official Build) (64-bit)]
- Screen Reader: [NVDA]

For screen readers, we primarily support the following combinations, and other combinations will be considered on a case by case basis.

- NVDA + Firefox (Windows)
- VoiceOver + Safari (Apple)

### PR DESCRIPTION
**Pull request by gnomeontherun**
This allows an application to disable the focus management on page change in cases where there are unexpected side effects. It is a requirement by default to have it on, so the setting is to disable it.

`<clr-datagrid [clrDgDisablePageFocus]="disableFocus"></clr-datagrid>`

closes #4229
closes #5374

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by bbogdanov — APPROVED** [review]

File: packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts [hunk 1]
```diff
@@ -158,6 +158,8 @@ export class ClrDatagrid<T = any> implements AfterContentInit, AfterViewInit, On
   @Input() clrDgSingleSelectionAriaLabel: string = this.commonStrings.keys.singleSelectionAriaLabel;
   @Input() clrDgSingleActionableAriaLabel: string = this.commonStrings.keys.singleActionableAriaLabel;
   @Input() clrDetailExpandableAriaLabel: string = this.commonStrings.keys.detailExpandableAriaLabel;
+  // Allows disabling of the auto focus on page/state changes (excludes focus management inside of popups)
+  @Input() clrDgDisableAutoFocus = false;
```
Comment (Shijir) [inline packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts]: Can't we specifically say `clrDgDisablePageFocus`?

**Review by Shijir — APPROVED** [review]

File: packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts (hunk 1 above)
Comment (gnomeontherun) [reply packages/angular/projects/clr-angular/src/data/datagrid/datagrid.ts]: I'll change it, thanks for the suggestion.
