### PR TITLE
fix(wizard): prevent closing non closable wizards

### LINKED ISSUE #3499: Wizard can be closed with ESC key even when nonclosable
## Describe the bug

When setting a wizard to non-closable, it can still be closed via ESC key. See https://github.com/vmware/clarity/issues/478

## How to reproduce

- Go to https://v1.clarity.design/wizards
- Using the keyboard alone, activate the WIZARD, NOT CLOSABLE button under the Non-Closable Wizard example
- Press the Escape key and observe that Wizard modal closes and a native browser alert appears asking "Do you really, really want to close the wizard?"
- Activate the OK button and observe the wizard close.

## Expected behavior

Remove the ability to use the Escape key to close the wizard when using [clrWizardClosable]="false".

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

This seems like a regression.

### PR DESCRIPTION
**Pull request by coryrylan**
Prevent non closable wizards from closing with
the escape key.

closes #3499

Signed-off-by: Cory Rylan <crylan@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

* [x] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

When disabling a wizard from closing the user could still close by using the escape key.

Issue Number: N/A

## What is the new behavior?
When the wizard is not closable the wizard will not close after pressing the escape key.

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

### CODE REVIEW

File: src/clr-angular/wizard/wizard.ts [hunk 1]
```diff
@@ -393,7 +393,9 @@ export class ClrWizard implements OnDestroy, AfterContentInit, DoCheck {
    * alternative cancel functionality. In most cases, use `ClrWizard.cancel()` instead.
    */
   public modalCancel(): void {
-    this.checkAndCancel();
+    if (this.closable) {
+      this.checkAndCancel();
```
Comment (gnomeontherun) [inline src/clr-angular/wizard/wizard.ts]: Why wouldn't this check go into the `checkAndCancel` method?

Comment (coryrylan) [reply src/clr-angular/wizard/wizard.ts]: I wasn't sure about putting it into the `checkAndCancel` method because it is public and not used in the template. It seemed like a convenience method for developers to call. I was thinking if that was the case then calling `wizard.checkAndCancel()` programmatically should cancel the wizard regardless if the wizard is in a closable state.
