### PR TITLE
fix(angular:datagrid): focus error on the button when details is open…

### LINKED ISSUE #6293: Datagrid spams TypeErrors in the browser console
## Describe the bug

When a user clicks on a globally available refresh button, we ought to display the newly fetched information from the server (due to the reason that sometimes it may be stale). The current example does not make use of xhrs, thus the timeout.
Clicking on the refresh button populates the datagrid with new items.
Expanding and/or hiding the pane, produces the following errors in the browser console:  
ERROR TypeError: this.button.focus is not a function.

## How to reproduce

I am able to reproduce this in the stackblitz example by clicking on the refresh button, and opening / closing the pane.

1. Open the provided example
2. Click on the refresh button
3. Expand or retract the datagrid pane and observe the error in the browser console

## Expected behavior

There should be no errors in the browser console, and the button should have a correct type.

## Versions

**Clarity project:**

- [] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12, Clarity 5

**Device:**

- Type: MacBook
- OS: iOS
- Browser: Chrome
- Version: 92.0.x

## Additional notes

Link to stackblitz: https://stackblitz.com/edit/clarity-light-theme-v5-g22fad

### PR DESCRIPTION
**Pull request by bbogdanov**
Closes #6293

Signed-off-by: Bogdan Bogdanov <bbogdanov@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: projects/angular/src/data/datagrid/datagrid-row.ts [hunk 1]
```diff
@@ -170,7 +171,7 @@ export class ClrDatagridRow<T = any> implements AfterContentInit, AfterViewInit
     }
   }
 
-  @ViewChild('detailButton') detailButton: HTMLButtonElement;
+  @ViewChild('detailButton') detailButton: DebugElement;
```
Comment (bdryanovski) [inline projects/angular/src/data/datagrid/datagrid-row.ts]: Why `DebugElement`

**Review by bdryanovski — CHANGES_REQUESTED** [review]

**Review by bdryanovski — APPROVED** [review]

**Review by Jinnie — APPROVED** [review]
