### PR TITLE
fix: accept clrLabelSize values provided without binding

### LINKED ISSUE #4432: Directive clrLabelSize doesn't work
## Describe the bug

I've tried to use **clrLabelSize="6"** but it doesn't change a label class from `clr-col-md-2` to `clr-col-md-6`

## How to reproduce

https://stackblitz.com/edit/angular-zxgdaa?file=src/app/app.component.html

A label tag has class `clr-col-md-2`.

## Expected behavior

A label tag should have class `clr-col-md-4`.

## Versions

**App**

* Angular: 8.2.14
* Clarity: 3.0.1

**Device:**

* Type: PC
* OS: Ubuntu 19.10
* Browser Google Chrome
* Version 80.0.3987.162

### PR DESCRIPTION
**Pull request by sis0k0**
Signed-off-by: Stanimira Vlaeva <svlaeva@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Values provided without binding are ignored:

```
<form clrForm clrLayout="horizontal" clrLabelSize="6">
```

Issue Number: #4432

## What is the new behavior?

Values provided without binding are converted to numbers and set as the size.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

closes #4432

### CODE REVIEW

File: packages/angular/projects/clr-angular/src/forms/common/form.ts [hunk 1]
```diff
@@ -20,8 +20,9 @@ import { ClrLabel } from './label';
 })
 export class ClrForm {
   @Input('clrLabelSize')
-  set labelSize(size: number) {
-    this.layoutService.labelSize = size;
+  set labelSize(size: number | string) {
+    const sizeNumber = parseInt(size as string);
```
Comment (bbogdanov) [inline packages/angular/projects/clr-angular/src/forms/common/form.ts:24]: We will need to cover the case when `size` is `''`.  `paseInt` will return `NaN`

Comment (sis0k0) [reply packages/angular/projects/clr-angular/src/forms/common/form.ts:24]: There's additional validation in `LayoutService`. If the value is `NaN`, it won't be set.

**Review by bbogdanov — APPROVED** [review]

File: packages/angular/projects/clr-angular/src/forms/common/form.ts (hunk 1 above)
Comment (bdryanovski) [reply packages/angular/projects/clr-angular/src/forms/common/form.ts:24]:
```js
const sizeNumber = parseInt(size as string, 10) || 0;
```

* handle the `NaN` case by setting it to 0 when it could not find a number for it (if there is some default value of size - better use it then 0 .. it's just an example)
* setting `radix` will handle the conversion when it comes to passing strange forms of numbers ;) 

```js
parseInt("09", 8) 
// => 0
parseInt("09", 10)
// => 9
```
Not all browser will use default `10`

Comment (sis0k0) [reply packages/angular/projects/clr-angular/src/forms/common/form.ts]: Thanks! I've updated the PR.

File: packages/angular/projects/clr-angular/src/forms/common/form.ts [hunk 2]
```diff
@@ -20,8 +20,9 @@ import { ClrLabel } from './label';
 })
 export class ClrForm {
   @Input('clrLabelSize')
-  set labelSize(size: number) {
-    this.layoutService.labelSize = size;
+  set labelSize(size: number | string) {
+    const sizeNumber = parseInt(size as string, 10) || 0;
```
Comment (gnomeontherun) [inline packages/angular/projects/clr-angular/src/forms/common/form.ts:24]: We should default to the default label size (2 I believe) otherwise this would generate an invalid label size of 0.

Comment (sis0k0) [reply packages/angular/projects/clr-angular/src/forms/common/form.ts]: Good catch! I've updated it to `2`.

**Review by bdryanovski — APPROVED** [review]

File: packages/angular/projects/clr-angular/src/forms/common/form.ts [hunk 3]
```diff
@@ -20,8 +20,9 @@ import { ClrLabel } from './label';
 })
 export class ClrForm {
   @Input('clrLabelSize')
-  set labelSize(size: number) {
-    this.layoutService.labelSize = size;
+  set labelSize(size: number | string) {
+    const sizeNumber = parseInt(size as string, 10) || 2;
+    this.layoutService.labelSize = sizeNumber;
```
Comment (bdryanovski) [inline packages/angular/projects/clr-angular/src/forms/common/form.ts:25]: This really super minor but why we need the variable here ? ;)

```ts
this.layoutService.labelSize = parseInt(size as string, 10) || 2;
```

**Comment by sis0k0** [comment]
@gnomeontherun, I've applied the requested changes.

**Comment by mathisscott** [comment]
@sis0k0 
What versions is this going into?

Will we have it merged for tomorrow's release?

**Comment by sis0k0** [comment]
@mathisscott, since it's not a breaking change anymore, I suggest we include it in the next patch.
