### PR TITLE
[NG] fix datepicker in table css issue

### LINKED ISSUE #2765: Date picker display issues when used inside table (chrome, firefox)
## Describe the bug

When using the date picker inside of a table, some colums inside the date picker are not shown.

## How to reproduce

```html
<table class="table">
   <tbody>
       <tr>
         <td>
            <input type="date" clrDate>
         </td>
       </tr>
   </tbody>
</table>
```

https://stackblitz.com/edit/clarity-light-theme-v013-6thcd1?file=src/app/app.component.html

## Expected behavior

All columns of the month are shown.

## Versions

**App**

* Clarity: 0.13 (0.11 also does not work)

**Device:**

* OS: Ubuntu 18.04
* Browser Firefox 62, Chrome

### PR DESCRIPTION
**Pull request by coryrylan**
When a datepicker is nested in a table it should render properly. The table styles were leaking into the datepicker table elements. This is now corrected.

closes #2765

Signed-off-by: Cory Rylan <crylan@vmware.com>

### CODE REVIEW

File: gemini/tests/set1/datepicker.js [hunk 1]
```diff
@@ -106,4 +107,18 @@ gemini.suite('datepicker', child => {
...
       .capture('default');
   });
+
+  gemini.suite('datepicker nested in table', child => {
+    child
+      .setUrl('/datepicker/css-regression')
+      .before((actions, find) => {
+        actions.waitForElementToShow('.clr-example-3', WAIT_TIME);
+        actions.wait(WAIT_LOAD_TIME);
+        this.trigger = find('.clr-example-3 .datepicker-trigger');
```
Comment (Jinnie) [inline gemini/tests/set1/datepicker.js]: Just curious, can anyone tell me why are we using this.trigger instead of local variable here and elsewhere in these tests? Better garbage collection?

File: src/clr-angular/forms/datepicker/_datepicker.clarity.scss [hunk 2]
```diff
@@ -107,7 +107,8 @@
     width: 100%;
   }
 
-  .calendar-cell {
+  .calendar-cell,
+  .calendar-table .calendar-cell {
```
Comment (youdz) [inline src/clr-angular/forms/datepicker/_datepicker.clarity.scss]: Ha, simple as that. 😁 

👍

**Comment by Jinnie** [comment]
Won't we be merging this?
