### PR TITLE
fix: (combobox) simplify control state management

### LINKED ISSUE #5101: Stepper resets when having a combobox inside.
## Describe the bug

Stepper resets when having a combobox inside.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-zaowaw

1.  Go to https://stackblitz.com/edit/clarity-v4-light-theme-zaowaw
2.  Click on Next
3.  Select a value from combobox
4.  Stepper resets to first panel

If you change anything in first step to make the form non-pristine, it works as expected.

## Expected behavior

Stepper should not reset

## Versions

**App**

- Angular: 10.0.6
- Node: 8
- Clarity: 4.0.0-rc.1 (inside stackblitz, as I can't update there), but also on latest 4.0.2

**Device:**

- Type: MacBook
- OS: macOS
- Browser chrome, safari

## Additional notes

The listener in stepper for form status changes resets the panel, as the form is pristine.
https://github.com/vmware/clarity/blob/master/packages/angular/projects/clr-angular/src/accordion/stepper/stepper.ts#L76

Seems that the combobox control update which sets the form to non-pristine is after the check above.

### PR DESCRIPTION
**Pull request by Jinnie**
It was leading to lifecycle calls overhead in incorrect intermediate states.
closes: #5101
Signed-off-by: Ivan Donchev <idonchev@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

There are intermediate pristine state changes, which get caught by the Stepper and it resets itself.

Issue Number: #5101 

## What is the new behavior?

All direct control-manipulations are removed and communication with the forms API goes only through the ControlValueAccessor interface. Stepper does not reset.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/angular/projects/clr-angular/src/forms/combobox/combobox.ts [hunk 1]
```diff
@@ -318,8 +310,8 @@ export class ClrCombobox<T> extends WrappedFormControl<ClrComboboxContainer>
   }
 
   private updateControlValue() {
-    if (this.control && this.control.control) {
-      this.control.control.setValue(this.optionSelectionService.selectionModel.model);
+    if (this.onChangeCallback) {
```
Comment (bdryanovski) [inline packages/angular/projects/clr-angular/src/forms/combobox/combobox.ts:313]: nit: 

I will change here is `onChangeCallback` a function before trying to call like one.

We use `any` to define the type so there is no guarantee that this won't throw `is not a function error`

**Review by bdryanovski — APPROVED** [review]

File: packages/angular/projects/clr-angular/src/forms/combobox/combobox.ts (hunk 1 above)
Comment (Jinnie) [reply packages/angular/projects/clr-angular/src/forms/combobox/combobox.ts:313]: Thanks! It's only public, because the interface handler is, but it's not supposed to be overwritten by the users. It gets injected by the forms API.
Not that the suggestion is bad, but I don't expect it to lead to problems. If someone overrides with something else - he'll get no worse exception than the one I could give him.

**Review by bbogdanov — APPROVED** [review]

**Review by sis0k0 — APPROVED** [review]
