### PR TITLE
fix(date-picker): prevent calling for focus, when date-picker is closed

### LINKED ISSUE #4060: Datepicker steals focus when hitting escape
## Describe the bug

When using a date picker it always listens for the escape key, even when closed. 

When hitting the escape key when the date picker is closed it will focus on the little calendar icon. If the date-picker is out of view the page will scroll to the picker.

## How to reproduce

1. https://v2.clarity.design/datepicker
2. Hit escape
3. The focus will shift to the first available date picker

## Expected behavior

Nothing should happen when the picker is closed.

## Versions

Reproducible on Clarity 2.3.2 and Angular 8.2.14

### PR DESCRIPTION
**Pull request by bdryanovski**
Prevent from calling focus on date picker when the calendar is not open (depend on ifOpenService)

## PR Checklist

Please check if your PR fulfills the following requirements:

* [x] Tests for the changes have been added (for bug fixes / features)
* [ ] Docs have been added / updated (for bug fixes / features)
* [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

* [x] Bugfix
* [ ] Feature
* [ ] Code style update (formatting, local variables)
* [ ] Refactoring (no functional changes, no api changes)
* [ ] Build related changes
* [ ] CI related changes
* [ ] Documentation content changes
* [ ] clarity.design website / infrastructure changes
* [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #4060 

## What is the new behavior?

track ifOpenService state and prevent requesting for focus.

## Does this PR introduce a breaking change?

* [ ] Yes
* [x] No

## Other information

Close #4060

### CODE REVIEW

File: src/clr-angular/forms/datepicker/date-container.ts [hunk 1]
```diff
@@ -131,7 +133,9 @@ export class ClrDateContainer implements DynamicWrapper, OnDestroy {
 
   @HostListener('body:keyup.escape')
   close(): void {
-    this.toggleButton.nativeElement.focus();
+    if (this.isOpen === true) {
```
Comment (hippee-lee) [inline src/clr-angular/forms/datepicker/date-container.ts]: Could this be reduced to just:
```
if (this.isOpen) { ... } 
```

Comment (bdryanovski) [reply src/clr-angular/forms/datepicker/date-container.ts]: Sure, 
I have this mental note in my head to write sometimes like that to simplify my head compiler :)

will push fix tomorrow morning

**Comment by martinbrom** [comment]
You also need to set the local isOpen variable back to false, otherwise this happens.

Clarity-GoogleChrome2019-12-0512

**Comment by martinbrom** [comment]
Still the same issue after your last change. It only works when Escape key is used to close the date picker modal. If you close it by clicking outside of it, the scrolling problem occurs.

**Comment by bdryanovski** [comment]
We gonna discuss this in our daily meeting to see what we could do about it.

File: src/clr-angular/forms/datepicker/date-container.ts [hunk 2]
```diff
@@ -129,9 +133,13 @@ export class ClrDateContainer implements DynamicWrapper, OnDestroy {
     );
   }
 
-  @HostListener('body:keyup.escape')
-  close(): void {
-    this.toggleButton.nativeElement.focus();
+  @HostListener('keydown', ['$event'])
```
Comment (hippee-lee) [inline src/clr-angular/forms/datepicker/date-container.ts]: Lets get rid of this listener and just react to the ifOpenService.openChange subscription. The subscribe may need to move to afterViewInit but it could look like this:

```
this._ifOpenService.openChange.subscription(open => {
  if(open) {
    this.initializeCalendar();
  } else {
    this.toggleButton.nativeElement.focus()
  }
})
```

This way we can get rid of the host listener and still react to open/close changes as needed because the host listener wasn't actually closing the datepicker conteiner.

Comment (bdryanovski) [reply src/clr-angular/forms/datepicker/date-container.ts]: We could remove but there is one side effect - it's when you click outside the calendar we gonna get back the focus to the calendar icon. So if this is ok... it's a lot simple to just re-use the `if-else` block.

The above change also will remove the need for zones.

I gonna push PR with that change and we don't like it we could always revert the last commit

**Comment by bdryanovski** [comment]
I have a failing test - will try to fix it before monday
