### PR TITLE
fix: numberic filters type was not applyed on dg-column

### LINKED ISSUE #4567: clrDgColType='number' broken
## Describe the bug

clrDgColType='number' is not doing any actual filtering

## How to reproduce

https://stackblitz.com/edit/clr-basic-datagrid-4zdewf?file=src%2Fapp%2Fbasic-datagrid.component.html

1.  Go to stackblitz above
2.  Click on id filter
3.  Enter any value
4.  See no filtering happening

## Expected behavior

Rows filtered according to filter input

## Versions

**App**

- Angular: 8
- Clarity: 2.4.2

## Additional notes

Same breakage visible in the official docs: https://clarity.design/documentation/datagrid/binding-properties
The filter on the 'wins' column is broken

### PR DESCRIPTION
**Pull request by bdryanovski**
The order of the `@Input` needed to be changed, cause we are asking for a `colType` before it was assigned so it always defaulted to `string`

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #4567

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Close #4567

### CODE REVIEW

File: src/clr-angular/data/datagrid/datagrid-column.ts [hunk 1]
```diff
@@ -126,6 +126,15 @@ export class ClrDatagridColumn<T = any> extends DatagridFilterRegistrar<T, ClrDa
...
   }
 
+  /*
+  * What type is this column?  This defaults to STRING, but can also be
+  * set to NUMBER.  Unsupported types default to STRING. Users can set it
+  * via the [clrDgColType] input by setting it to 'string' or 'number'.
+  */
+
+  // TODO: We might want to make this an enum in the future
+  @Input('clrDgColType') colType: 'string' | 'number' = 'string';
```
Comment (gnomeontherun) [inline src/clr-angular/data/datagrid/datagrid-column.ts:136]: Would be nice to have a test for this.

**Comment by gnomeontherun** [comment]
Typos in commit message.
