### PR TITLE
Fix tree view flickering from async eventemitter

### LINKED ISSUE #3073: Tree View - Checkbox Tree "Flickering"
## Describe the bug

When the checkbox on the top node is clicked multiple times (quite quickly), the checkboxes of the child nodes start to "flicker".

## How to reproduce

[Stackblitz Example](https://stackblitz.com/edit/clarity-dark-theme-v1-0-treeview-issue)

1.  Click checkbox on node "Group A" twice very quickly (like a double click)
2.  Again, click checkbox on node "Group A" twice very quickly
3.  Note that the checkboxes of the child nodes start to flicker endlessly

## Expected behavior

No "flickering" should occur.

## Versions

**App**

* Angular: 7.2.0
* Node: ?
* Clarity: 1.0.4

**Device:**

* Type: HP zBook
* OS: Windows 10
* Browser Chrome
* Version 71.0.3578.98 (64-Bit)

## Additional notes

The problem seems to get worse the more components are present on the page. As it might be difficult to reproduce the issue on another environment, I'm attaching a screen capture from my machine.

[Tree View Flickering Video Capture.zip](https://github.com/vmware/clarity/files/2796344/Tree.View.Flickering.Video.Capture.zip)

### PR DESCRIPTION
**Pull request by gnomeontherun**
fix(tree) set tree view node event emitter to synchronous and don't output selected changes when setting input on node

A tree view with a number of nodes could be tricked into a state of uncertainty (flickering) by double clicking fast to trigger too many async event loops in the bindings. This stops the event propagation from firing in this specific case, but keeps it in the remainder where it is needed to update other nodes.

fixes #3073

### Release notes

Bugfix for tree view where it could trigger a flickering state by double clicking fast, or in any case where the tree tried to update before the tree had stabilized.

### CODE REVIEW

File: src/clr-angular/data/tree-view/tree-node.ts [hunk 1]
```diff
@@ -90,12 +92,15 @@ export class ClrTreeNode<T> implements OnInit, OnDestroy {
...
     }
-    // We propagate only if the tree is in smart mode
+    // We propagate only if the tree is in smart mode, and skip emitting the output when we set the input
+    // See https://github.com/vmware/clarity/issues/3073
+    this.skipEmitChange = true;
     this._model.setSelected(value, this.featuresService.eager, this.featuresService.eager);
+    this.skipEmitChange = false;
   }
 
   // We need an async EventEmitter or we will trigger chocolate errors like it's 2016.
```
Comment (youdz) [inline src/clr-angular/data/tree-view/tree-node.ts]: Please remove this obsolete comment.

File: src/clr-angular/data/tree-view/tree-node.spec.ts [hunk 2]
```diff
@@ -163,19 +165,34 @@ export default function(): void {
...
+      it('offers a [(clrSelected)] two-way binding', function(this: Context) {
+        // Here we are testing the child two-way binding, which should be updated by two-way always.
+        const child = this.fixture.debugElement.query(By.directive(ClrTreeNode));
+        this.hostComponent.selected = ClrSelectedState.SELECTED;
+        this.detectChanges();
+        expect(this.clarityDirective.selected).toBe(ClrSelectedState.SELECTED);
+        expect(child.componentInstance.selected).toBe(ClrSelectedState.SELECTED);
+        this.clarityDirective.selected = ClrSelectedState.UNSELECTED;
+        this.detectChanges();
+        expect(child.componentInstance.selected).toBe(ClrSelectedState.UNSELECTED);
```
Comment (youdz) [inline src/clr-angular/data/tree-view/tree-node.spec.ts]: Testing the child here seems to have nothing to do with the current unit test. I get that the line 
```typescript
this.clarityDirective.selected = ClrSelectedState.UNSELECTED;
```
doesn't actually trigger the output for the parent, but this test relies on the entire logic of downward propagation of selection for eager trees, which feels wrong for a pure two-way binding test.

I think the next unit test you added covers the two-way binding, so you can remove this one or change it to describe more specifically what you're testing (presumably chocolate errors?).

File: src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts [hunk 3]
```diff
@@ -41,12 +44,25 @@ export class EagerRecursiveTreeDemo {
     },
   ];
 
-  singleRootSelected: { [key: string]: ClrSelectedState } = {};
-  multiRootSelected: { [key: string]: ClrSelectedState } = {};
+  private buildDefaultSelected(rootMap, selectedMap: SelectedMap = {}) {
+    if (!Array.isArray(rootMap)) {
+      rootMap = [rootMap];
```
Comment (Shijir) [inline src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts]: In this case of `!Array.isArray(rootMap)`, `rootMap` is `nodelist`, no? Shouldn't we do `Array.from(rootMap)` instead of `[rootMap]`?

File: src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts [hunk 4]
```diff
@@ -41,12 +44,25 @@ export class EagerRecursiveTreeDemo {
     },
   ];
 
-  singleRootSelected: { [key: string]: ClrSelectedState } = {};
-  multiRootSelected: { [key: string]: ClrSelectedState } = {};
+  private buildDefaultSelected(rootMap, selectedMap: SelectedMap = {}) {
```
Comment (Shijir) [inline src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts]: Can we have a type on `rootMap` parameter?

File: src/clr-angular/data/tree-view/tree-node.spec.ts (hunk 2 above)
Comment (gnomeontherun) [reply src/clr-angular/data/tree-view/tree-node.spec.ts]: Since the selection will propigate to the child, I'm testing that as the two way binding to get around the input change limitation I'm testing in the other test. If you're happy with the second test then I'll just remove this one.

File: src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts (hunk 3 above)
Comment (gnomeontherun) [reply src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts]: `rootMap` is either an array or an object, see the `singleRoot` and `multiRoot` properties on the class.

File: src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts (hunk 4 above)
Comment (gnomeontherun) [reply src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts]: Added.

File: src/clr-angular/data/tree-view/tree-node.ts (hunk 1 above)
Comment (gnomeontherun) [reply src/clr-angular/data/tree-view/tree-node.ts]: Done.

File: src/clr-angular/data/tree-view/tree-node.ts [hunk 5]
```diff
@@ -90,12 +92,15 @@ export class ClrTreeNode<T> implements OnInit, OnDestroy {
...
-  @Output('clrSelectedChange') selectedChange = new EventEmitter<ClrSelectedState>(true);
+  @Output('clrSelectedChange') selectedChange = new EventEmitter<ClrSelectedState>(false);
```
[the remark this answers is not in the document]
Comment (gnomeontherun) [reply src/clr-angular/data/tree-view/tree-node.ts]: I know, but decided to leave it to be clear that we want it false.

File: src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts (hunk 3 above)
Comment (Shijir) [reply src/dev/src/app/tree-view/eager-recursive-tree/eager-recursive-tree.ts]: But on line 51, we have `this.buildDefaultSelected(node.children, selectedMap);` 
So we are basically putting `node.children`, which is `NodeList` in the array.
